spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(AYkJuQ2c0zwJnHxg3Aj4J3T/qFa+oAhD3w4xQlQpJ3vHtVe/7+US+MokaBNhIgpi)
    username: ENC(9aLAPbkgLiKrHC1tNQF/vw==)
    password: ENC(lBuJ5vvF1rlLDNYLcK+aew==)
      
  
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    